version: '3.9'

services:
  sport_session_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6700:5432
    networks:
      - sport_session_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  sport_session:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 6750:80
    networks:
      - sport_session_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
    depends_on:
      sport_session_db:
        condition: service_started

networks:
  sport_session_net:
    driver: bridge
    name: sport_session_net