name: Unit tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  test_sport_session:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t sport-session-image .
      - name: Test
        run: docker run --rm --network="host" -e TEST=true -e SPORT_SESSION_DB_HOST='localhost' -e SPORT_SESSION_DB_PORT='5432' -e SPORT_SESSION_DB_PASSWORD='postgres' -e SPORT_SESSION_DB_USER='postgres' -e SPORT_SESSION_DB_NAME='postgres' sport-session-image
